### PR TITLE
Add localization for Vietnamese

### PR DESCRIPTION
**Pull request by rcgary**
- Add localization for Vietnamese

### CODE REVIEW

**Comment by yannickl** [comment]
Hi, sorry for the late,

Can you add the test file with the localization?

Best

**Comment by yannickl** [comment]
I can't merge your pull if you don't add the corresponding test file. You can take example on this one: https://github.com/yannickl/YLMoment/blob/master/Tests/Tests/Lang/YLMomentTest%2BLangEn.m.

When do you think to be able to do this?

**Comment by rcgary** [comment]
Hi @yannickl 

Sorry that I have not noiced this. Will do it on this weekend!

**Comment by yannickl** [comment]
Sorry for the late. Thank you very much for your help!

**Pull request merged**
